# Scala CircleCI 2.0 configuration file
#
version: 2.1
jobs:
  build-latest-lib-and-test:
    docker:
      - image: innfactory/gcloud-scala-ci:11.0.6
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx4096m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.sbt" }}
            - v1-dependencies-
      - run:
          name: background datastore for tests
          command: gcloud beta emulators datastore start --no-store-on-disk --consistency=1.0
          background: true
      - run:
          name: Build latest akka-persistence-gcp-datastore lib from master
          command: |
            cd $HOME
            git clone https://$GIT_USER:$GIT_SSHKEY@github.com/innFactory/akka-persistence-gcp-datastore-example.git
            cd $HOME/akka-persistence-gcp-datastore-example
            sbt test
            sbt publishLocal
            echo 'export GCP_PLUGIN_VERSION="$(sbt version | tail -1 | egrep -o \"[0-9].[0-9].[0-9]\")"' >> $BASH_ENV
            source $BASH_ENV
            echo "Current Plugin Version is: ${GCP_PLUGIN_VERSION}"
            cd ..
      - run:
          name: clear datastore
          command:
            curl -X POST http://localhost:8081/reset
      - run:
          name: run example tests
          command: |
            sbt -DGCP_PLUGIN_VERSION=${GCP_PLUGIN_VERSION} test
      - save_cache:
          paths:
            - "~/.iv2/cache"
            - "~/.sbt"
            - "~/.m2"
          key: v1-dependencies-{{ checksum "build.sbt" }}
workflows:
  version: 2
  akka-persistence-gcp-datastore-example-pipeline:
    jobs:
      - build-latest-lib-and-test